services:
  - type: web
    name: project-hub-x
    env: node
    buildCommand: |
      npm install &&
      npm --prefix project-hub-x install &&
      node tools/generate-mockdata-from-content.mjs &&
      npm --prefix project-hub-x run build
    startCommand: |
      cd project-hub-x && npm run preview -- --host 0.0.0.0 --port $PORT
    envVars:
      - key: NODE_VERSION
        value: 18
    autoDeploy: true
